version: '3.8'

services:
  strftimeapi:
    image: ghcr.io/rondie/strftimeapi:latest
    container_name: strftimeapi
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1